function addDays(days) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

export async function createSeedData(hashPassword) {
  const now = new Date().toISOString();
  const [adminHash, defaultProfessorHash] = await Promise.all([
    hashPassword("admin123"),
    hashPassword("123456"),
  ]);

  return {
    users: [
      {
        id: 1,
        nome: "Administrador",
        matricula: "000000",
        curso: "Coordenação",
        role: "admin",
        passwordHash: adminHash,
        ativo: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 2,
        nome: "Maria Silva",
        matricula: "2026001",
        curso: "Informática",
        role: "professor",
        passwordHash: defaultProfessorHash,
        ativo: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 3,
        nome: "Joao Costa",
        matricula: "2026002",
        curso: "Administração",
        role: "professor",
        passwordHash: defaultProfessorHash,
        ativo: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 4,
        nome: "Patricia Alves",
        matricula: "2026003",
        curso: "Redes",
        role: "professor",
        passwordHash: defaultProfessorHash,
        ativo: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
    labs: [
      {
        id: 1,
        nome: "Laboratório 01 - Informática",
        tipo: "Informática",
        capacidade: 30,
        localizacao: "Bloco A",
        recursos: ["Computadores", "Projetor", "Internet"],
        ativo: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 2,
        nome: "Laboratório 02 - Matemática",
        tipo: "Matemática",
        capacidade: 25,
        localizacao: "Bloco B",
        recursos: ["Calculadoras", "Kit geométrico"],
        ativo: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 3,
        nome: "Laboratório 03 - Química",
        tipo: "Química",
        capacidade: 20,
        localizacao: "Bloco C",
        recursos: ["Microscópios", "Reagentes"],
        ativo: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 4,
        nome: "Laboratório 04 - Física",
        tipo: "Física",
        capacidade: 24,
        localizacao: "Bloco C",
        recursos: ["Kits de circuitos", "Sensores"],
        ativo: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
    reservations: [
      {
        id: 1,
        userId: 2,
        labId: 1,
        data: addDays(4),
        inicio: "08:00",
        termino: "10:00",
        quantidadeAlunos: 24,
        status: "aprovada",
        observacao: "Aula prática",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 2,
        userId: 3,
        labId: 4,
        data: addDays(4),
        inicio: "10:00",
        termino: "12:00",
        quantidadeAlunos: 20,
        status: "aprovada",
        observacao: "Experimento guiado",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 3,
        userId: 4,
        labId: 2,
        data: addDays(5),
        inicio: "14:00",
        termino: "16:00",
        quantidadeAlunos: 22,
        status: "aprovada",
        observacao: "Resolução de exercícios",
        createdAt: now,
        updatedAt: now,
      },
    ],
    problems: [
      {
        id: 1,
        labId: 2,
        userId: 2,
        tipo: "TV com defeito",
        descricao: "A TV não liga durante a aula.",
        status: "aberto",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 2,
        labId: 1,
        userId: 3,
        tipo: "Internet lenta",
        descricao: "Conexão instável no turno da tarde.",
        status: "em_andamento",
        createdAt: now,
        updatedAt: now,
      },
    ],
    inventory: [
      { id: 1, labId: 1, item: "Computadores", disponivel: 22, indisponivel: 3, createdAt: now, updatedAt: now },
      { id: 2, labId: 1, item: "Computadores reserva", disponivel: 2, indisponivel: 3, createdAt: now, updatedAt: now },
      { id: 3, labId: 2, item: "Calculadoras", disponivel: 18, indisponivel: 2, createdAt: now, updatedAt: now },
      { id: 4, labId: 2, item: "Kit geométrico", disponivel: 6, indisponivel: 1, createdAt: now, updatedAt: now },
      { id: 5, labId: 3, item: "Microscópios", disponivel: 8, indisponivel: 2, createdAt: now, updatedAt: now },
      { id: 6, labId: 3, item: "Kit de reagentes", disponivel: 5, indisponivel: 3, createdAt: now, updatedAt: now },
      { id: 7, labId: 4, item: "Kits de circuitos", disponivel: 10, indisponivel: 2, createdAt: now, updatedAt: now },
      { id: 8, labId: 4, item: "Sensores de movimento", disponivel: 4, indisponivel: 2, createdAt: now, updatedAt: now },
    ],
    accesses: [],
  };
}
